-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-06-16 09:52:50.832

-- foreign keys
ALTER TABLE ARVE
    DROP FOREIGN KEY ARVE_ISIK;

ALTER TABLE ARVE_RIDA
    DROP FOREIGN KEY ARVE_RIDA_ARVE;

ALTER TABLE ARVE_RIDA
    DROP FOREIGN KEY ARVE_RIDA_TALU_TOODE;

ALTER TABLE TALU_TOODE
    DROP FOREIGN KEY TALU_TOODE_TALU;

ALTER TABLE TALU_TOODE
    DROP FOREIGN KEY TALU_TOODE_TOODE;

-- tables
DROP TABLE ARVE;

DROP TABLE ARVE_RIDA;

DROP TABLE ISIK;

DROP TABLE TALU;

DROP TABLE TALU_TOODE;

DROP TABLE TOODE;

-- End of file.

